upstream: https://some.repository.com/upstream/repo
verbose: true
modsdir: mymods
codemods:
- description: Modify URLS
  mod: sed
  match: cmd/*.go
  args:
  - github.com/upstream/repo
  - github.com/myfork/repo
ignorelist:
- prefix: ct/
