# https://taskfile.dev

version: '3'

vars:
  VERSION: 0.2.1

tasks:
  build:
    cmds:
      - go build -o surgeon -ldflags '-s -w -X github.com/bketelsen/surgeon/cmd.version={{.VERSION}}-dev' main.go 
    silent: true
  install-goreleaser:
    cmds:
      - wget https://github.com/goreleaser/goreleaser-pro/releases/download/v2.7.0-pro/goreleaser-pro_2.7.0_amd64.deb
      - sudo dpkg -i goreleaser-pro_2.7.0_amd64.deb 
      - rm goreleaser-pro_2.7.0_amd64.deb 
    silent: true
  release-snapshot:
    cmds:
      - goreleaser release --snapshot --clean
    silent: true
  release-check:
    cmds:
      - goreleaser check
    silent: true
  install:
    cmds:
      - go install .
    silent: true
  publish:
    cmds:
      - git push origin
      - git tag v{{.VERSION}}
      - git push --tags
  generate:
    cmds:
      - go run main.go docs -b "/surgeon"
    silent: true
  site:
    desc: Run hugo dev server
    deps: [build, generate]
    dir: docs
    cmds:
      - hugo server --buildDrafts --disableFastRender
