# https://taskfile.dev

version: '3'

vars:
  VERSION: 0.1.3

tasks:
  build:
    cmds:
      - go build -o surgeon .
    silent: true
  install:
    cmds:
      - go install .
    silent: true
  publish:
    cmds:
      - git push origin
      - git tag v{{.VERSION}}
      - git push --tags