# https://taskfile.dev
# Generated File, changes may be lost
# Add `Taskfile.custom.yml` in this directory with your additions

version: '3'

vars:
  VERSION: 0.2.3

includes:
  docs:
    taskfile: Taskfile.docs.yml
    optional: true
  checks:
    taskfile: Taskfile.checks.yml
    optional: true
  release:
    taskfile: Taskfile.release.yml
    optional: true
  custom:
    taskfile: Taskfile.custom.yml
    optional: true

tasks:


  setup:
    desc: Install dependencies
    cmds:
      - go mod tidy

  build:
    desc: Build the application
    summary: |
      Build the application with ldflags to set the version with a -dev suffix.

      Output: 'surgeon' in project root.
        sources:
      - ./**/*.go
    generates:
      - ./surgeon
    cmds:
      - go build

  tools:
    desc: Install required tools
    cmds:
      - go install github.com/bketelsen/toolbox/toolgen@latest

  direnv:
    desc: Add direnv hook to your bashrc
    cmds:
      - direnv hook bash >> ~/.bashrc
    silent: true

  generate:
    desc: Generate CLI documentation
    deps: [tools]
    cmds:
      - go run main.go gendocs -b "/surgeon"
    silent: true

